### ISSUE TITLE
Added SEA opcodes, Thx.

### ISSUE THREAD

**Issue by Daolh2610** [CattaLol/Tuwangi-Farmer#1]
Can you add SEA opcodes? Thanks u so much.

**Comment by CattaLol** [comment]
Opcodes can be logged with modules such as:
https://github.com/SoliaRdi/PacketsLogger
and/or
https://github.com/Owyn/alex-packet-id-finder

**Comment by Patricktheorge** [comment]
cattaLOL how to find this C_FIELD_EVENT_BAN
