### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by TetsuTt** [CattaLol/Tuwangi-Farmer#3]
I'm getting a lot of error in Proxy
I'll leave a link with the errors that are showing up
https://imgur.com/6znu94U

**Comment by CattaLol** [comment]
You do not have opcodes mapped. https://github.com/CattaLol/Tuwangi-Farmer#setup-opcodes

**Comment by TetsuTt** [comment]
that? Do I have to do anything else besides that?
https://imgur.com/WG8jUdt

**Comment by edhe15** [comment]
Hi CattaLol, i hve same problem with him...
Please tell me which part i missing..

I got all opcode u ask alredy.
![Untitled](https://user-images.githubusercontent.com/48638947/54882207-34373f00-4e8a-11e9-8b4b-60628a55dd9e.jpg)
