### ISSUE TITLE
HOW to proc this C_FIELD_EVENT_BAN

### ISSUE THREAD

**Issue by Patricktheorge** [CattaLol/Tuwangi-Farmer#4]

**Comment by CattaLol** [comment]
That is the afk-kick packet the client sends to the server when it receives no user input (for ~2 minutes) in a Guardian Legion event.

So... join a random Guardian Legion event and afk for a couple minutes with the logger on.

**Comment by Patricktheorge** [comment]
C_REQUEST_FIELD_POINT_REWARD this one? u need to accpet the reward ryt? sorry that i keep on asking
im at SEA

**Comment by CattaLol** [comment]
Correct. Accept a reward to proc that packet.
