### ISSUE TITLE
This mod still work?

### ISSUE THREAD

**Issue by edhe15** [CattaLol/Tuwangi-Farmer#7]
My mod doing nothing, just chat like this.
![Untitled](https://user-images.githubusercontent.com/48638947/54882816-7d8a8d00-4e90-11e9-8fc4-c030286dc554.jpg)
Im SEA server.

**Comment by edhe15** [comment]
Is it true this mod work by blink? or just visual?

**Comment by TetsuTt** [comment]
Usage:
Enable the module; go to the event zone; switch out of channel 1.

**Comment by CattaLol** [comment]
@edhe15 

1) This mod disables functioning in channel 1. Please exit and return the the event zone after switching out of channel 1.

2) This mod indeed functions by blinking you to the appropriate locations at the appropriate timings.

3) I have not provided opcodes for SEA region. You will need to map the missing opcodes yourself (see [here for the list of missing opcodes](https://github.com/CattaLol/Tuwangi-Farmer#setup-opcodes). You can find / log opcodes yourself with tools such as the [packets logger mod](https://github.com/SoliaRdi/PacketsLogger).

**Comment by edhe15** [comment]
C_SET_SEND_PARCEL_TYPE = 53239
C_SET_SEND_PARCEL_ITEM = 27380
C_SEND_PARCEL = 24573
C_FIELD_EVENT_BAN = 65292
C_REQUEST_FIELD_EVENT_REWARD = 60042
C_REQUEST_FIELD_POINT_REWARD = 38640

Can u teach me few script about how to auto take box, then auto tp to tuwangi location from velika or lumbertown.. 

I dont know which line that i need to change to make it work.
